/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.gui;

import java.sql.Connection;
import java.awt.*;
import javaswingdev.message.AlertGagal;
import javaswingdev.message.AlertPertanyaanHijau;

/**
 *
 * @author jinry
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Cursor();
        setFavIcon();
        Toolkit toolkit = getToolkit ();
        Dimension size = toolkit.getScreenSize();
        setLocation (size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);

   }
private void Cursor(){
buton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

}
void panggilAlertPertanyaan(String Title, String message){
            AlertPertanyaanHijau obj3 = new AlertPertanyaanHijau(this);
            obj3.showMessage(Title, message);
}
void panggilAlertMerah(String Title, String message){
            AlertGagal obj2 = new AlertGagal(this);
            obj2.showMessage(Title, message);
}

private void setFavIcon(){
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/img/Logoapp.png")));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pane = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        buton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko-Berkah Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        login_pane.setBackground(new Color(0,0,0,20));
        login_pane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_pane.setFocusCycleRoot(true);
        login_pane.setFocusTraversalPolicyProvider(true);
        login_pane.setMinimumSize(new java.awt.Dimension(1016, 615));
        login_pane.setPreferredSize(new java.awt.Dimension(1280, 720));
        login_pane.setLayout(null);

        txtuser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtuser.setForeground(new java.awt.Color(48, 56, 65));
        txtuser.setBorder(null);
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        login_pane.add(txtuser);
        txtuser.setBounds(90, 340, 470, 30);

        txtpass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtpass.setForeground(new java.awt.Color(48, 56, 65));
        txtpass.setBorder(null);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        login_pane.add(txtpass);
        txtpass.setBounds(90, 440, 470, 30);

        buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/btn-login.png"))); // NOI18N
        buton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                butonMouseReleased(evt);
            }
        });
        login_pane.add(buton);
        buton.setBounds(76, 515, 490, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/Inactive Field.png"))); // NOI18N
        login_pane.add(jLabel3);
        jLabel3.setBounds(80, 320, 490, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/Inactive Field.png"))); // NOI18N
        login_pane.add(jLabel5);
        jLabel5.setBounds(80, 430, 490, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/Group 166.png"))); // NOI18N
        login_pane.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void butonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonMouseClicked
        // TODO add your handling code here:
        String username = txtuser.getText().toString();
        String password = txtpass.getText().toString();

        try {
            String sql = "SELECT id_pengguna, password, jenis_pengguna"
            + " FROM pengguna"
            + " WHERE id_pengguna='" + username
            + "'AND password='" + password + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String user_tipe = rs.getString("jenis_pengguna");
                if (user_tipe.equals("Admin")) {
                    Dashboard dashboard = new Dashboard();
                    dashboard.nama.setText(rs.getString("id_pengguna"));
                    dashboard.setVisible(true);
                    this.dispose();
                } else if (user_tipe.equals("Karyawan")) {
                    Dashboardkar dashboardkar = new Dashboardkar();
                    dashboardkar.nama.setText(rs.getString("id_pengguna"));
                    dashboardkar.setVisible(true);
                    this.dispose();
                }
            } else {
                txtuser.requestFocus();
                //panggilAlertPertanyaan("Login Gagal !", "Username atau Password salah");
                panggilAlertMerah("Login Gagal !", "Username atau Password salah");

            }

        } catch (Exception e) {
                panggilAlertMerah("Login Gagal !", "Database belum terkoneksi");
            System.out.println("Error");
        }
    }//GEN-LAST:event_butonMouseClicked

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        // TODO add your handling code here:
if (txtuser.getText().equals("Masukkan Username Anda")) {
txtuser.setForeground(new java.awt.Color(51,51,51));
txtuser.setText("");
} else {
}
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
        // TODO add your handling code here:
if (txtuser.getText().equals("")) {
txtuser.setForeground(new java.awt.Color(221,221,221));
txtuser.setText("Masukkan Username Anda");
} else {
}
    }//GEN-LAST:event_txtuserFocusLost

    private void butonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonMouseEntered
        // TODO add your handling code here:
buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/btn-login-hover.png")));
    }//GEN-LAST:event_butonMouseEntered

    private void butonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonMouseExited
        // TODO add your handling code here:
buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/btn-login.png")));
    }//GEN-LAST:event_butonMouseExited

    private void butonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonMousePressed
        // TODO add your handling code here:
buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/btn-login-clicked.png")));
    }//GEN-LAST:event_butonMousePressed

    private void butonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonMouseReleased
        // TODO add your handling code here:
buton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/login/btn-login.png")));
    }//GEN-LAST:event_butonMouseReleased

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
        String username = txtuser.getText().toString();
        String password = txtpass.getText().toString();

        try {
            String sql = "SELECT id_pengguna, password, jenis_pengguna"
            + " FROM pengguna"
            + " WHERE id_pengguna='" + username
            + "'AND password='" + password + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String user_tipe = rs.getString("jenis_pengguna");
                if (user_tipe.equals("Admin")) {
                    Dashboard dashboard = new Dashboard();
                    dashboard.nama.setText(rs.getString("id_pengguna"));
                    dashboard.setVisible(true);
                    this.dispose();
                } else if (user_tipe.equals("Karyawan")) {
                    Dashboardkar dashboardkar = new Dashboardkar();
                    dashboardkar.nama.setText(rs.getString("id_pengguna"));
                    dashboardkar.setVisible(true);
                    this.dispose();
                }
            } else {
                txtuser.requestFocus();
                //panggilAlertPertanyaan("Login Gagal !", "Username atau Password salah");
                panggilAlertMerah("Login Gagal !", "Username atau Password salah");

            }

        } catch (Exception e) {
                panggilAlertMerah("Login Gagal !", "Database belum terkoneksi");
            System.out.println("Error");
        }
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtpassFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel login_pane;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
