/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javaswingdev.message.AlertBerhasil;
import javaswingdev.message.AlertGagal;
import javaswingdev.message.AlertPertanyaan;
import javaswingdev.message.AlertPertanyaanHijau;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author yogan
 */
public class TransaksiJualkar extends javax.swing.JFrame {
int popharga;
String jkdbar;
Double popqty;
private ImageIcon format = null;
    /**
     * Creates new form TransaksiJual
     */
    public TransaksiJualkar() {
        initComponents();
        setJkdtrans();
        settablejual();
        setJtgl();
        cekcartjual();
        jtfkdbat.requestFocus();
        popupjual.setVisible(false);
        checkout.setVisible(false);
        jPanel1.setVisible(true);
        Cursor();
        setFavIcon();
        Toolkit toolkit = getToolkit ();
        Dimension size = toolkit.getScreenSize();
        setLocation (size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    void Cursor(){
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
        pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popjtambahbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));       
        popjend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcaribar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jeditbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhpsbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        co_print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        co_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

private void setFavIcon(){
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/img/Logoapp.png")));
}

void setprofile() {
        try {
            String sql = "SELECT jenis_pengguna, img"
                    + " FROM pengguna"
                    + " WHERE id_pengguna='" + nama.getText() +"' ;" ;
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            jenis.setText(rs.getString(1));

            String imgsql = rs.getString(2);
//admin
            try{
            BufferedImage img = null;
            img = ImageIO.read(new File(imgsql));
            Image img1=img.getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH);
            format = new ImageIcon(img1);
            image.setIcon(format);
            }catch(Exception e){
            e.printStackTrace();
            }
//} else {
//
//}

        } catch (SQLException e) {
            e.printStackTrace();
        }
}

void panggilAlertHijau(String Title,String message){
            AlertBerhasil obj2 = new AlertBerhasil(this);
            obj2.showMessage(Title, message);
}
void panggilAlertMerah(String Title, String message){
            AlertGagal obj3 = new AlertGagal(this);
            obj3.showMessage(Title, message);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenis = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        gudang = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        pengaturan = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        popupjual = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablepopjual = new tabledark.TableDark();
        popjualcari = new javax.swing.JTextField();
        h = new javax.swing.JLabel();
        popjtftot = new javax.swing.JTextField();
        popjtfqty = new javax.swing.JTextField();
        popjend = new javax.swing.JLabel();
        popjtambahbar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        popjtfnamabar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        popjtfsat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkout = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        co_table = new tabledark.TableDark();
        co_isilblkiri = new javax.swing.JTextField();
        ta2 = new javax.swing.JLabel();
        co_print = new javax.swing.JLabel();
        co_back = new javax.swing.JLabel();
        co_kdtrans = new javax.swing.JLabel();
        co_isilblkanan = new javax.swing.JLabel();
        co_lblgtot = new javax.swing.JLabel();
        co_tgl = new javax.swing.JLabel();
        jualatas1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablejual = new tabledark.TableDark();
        jgatot = new javax.swing.JLabel();
        jtfqty = new javax.swing.JTextField();
        jtfharga = new javax.swing.JLabel();
        jtfsatuan = new javax.swing.JLabel();
        ta1 = new javax.swing.JLabel();
        jtftotal = new javax.swing.JLabel();
        jtfnamabar = new javax.swing.JLabel();
        jtfkdbar = new javax.swing.JLabel();
        jtfkdbat = new javax.swing.JTextField();
        jeditbar = new javax.swing.JLabel();
        jhpsbar = new javax.swing.JLabel();
        jcheckout = new javax.swing.JLabel();
        ta = new javax.swing.JLabel();
        jkdtrans = new javax.swing.JLabel();
        jcaribar = new javax.swing.JLabel();
        jtgl = new javax.swing.JLabel();
        jualatas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko-Berkah Transaksi Jual");
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        jenis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jenis.setForeground(new java.awt.Color(48, 56, 65));
        getContentPane().add(jenis);
        jenis.setBounds(1030, 60, 240, 30);

        nama.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(48, 56, 65));
        nama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                namaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(nama);
        nama.setBounds(1030, 30, 240, 30);

        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png"))); // NOI18N
        gudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gudangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gudangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gudangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gudangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gudangMouseReleased(evt);
            }
        });
        getContentPane().add(gudang);
        gudang.setBounds(21, 242, 200, 30);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/Transaction-jual.png"))); // NOI18N
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                transaksiMouseReleased(evt);
            }
        });
        getContentPane().add(transaksi);
        transaksi.setBounds(21, 201, 200, 30);

        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png"))); // NOI18N
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dashboardMouseReleased(evt);
            }
        });
        getContentPane().add(dashboard);
        dashboard.setBounds(21, 162, 200, 30);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(21, 454, 200, 30);

        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png"))); // NOI18N
        pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengaturanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengaturanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengaturanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pengaturanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pengaturanMouseReleased(evt);
            }
        });
        getContentPane().add(pengaturan);
        pengaturan.setBounds(21, 415, 200, 30);

        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png"))); // NOI18N
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                riwayatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                riwayatMouseReleased(evt);
            }
        });
        getContentPane().add(riwayat);
        riwayat.setBounds(21, 280, 200, 30);

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/kosong.png"))); // NOI18N
        getContentPane().add(Menu);
        Menu.setBounds(0, 100, 218, 630);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/Header.png"))); // NOI18N
        header.setAlignmentY(0.0F);
        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 110);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/default (1).png"))); // NOI18N
        getContentPane().add(image);
        image.setBounds(938, 10, 75, 90);

        popupjual.setBackground(new Color(0,0,0,20));
        popupjual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        popupjual.setFocusCycleRoot(true);
        popupjual.setFocusTraversalPolicyProvider(true);
        popupjual.setMinimumSize(new java.awt.Dimension(1016, 615));
        popupjual.setLayout(null);

        tablepopjual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepopjual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepopjualMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablepopjual);

        popupjual.add(jScrollPane4);
        jScrollPane4.setBounds(160, 90, 690, 380);

        popjualcari.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popjualcari.setBorder(null);
        popjualcari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                popjualcariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                popjualcariFocusLost(evt);
            }
        });
        popjualcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popjualcariActionPerformed(evt);
            }
        });
        popjualcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                popjualcariKeyReleased(evt);
            }
        });
        popupjual.add(popjualcari);
        popjualcari.setBounds(210, 40, 630, 30);

        h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/Search-bar-long.png"))); // NOI18N
        popupjual.add(h);
        h.setBounds(160, 30, 700, 50);

        popjtftot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popjtftot.setBorder(null);
        popjtftot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popjtftotActionPerformed(evt);
            }
        });
        popupjual.add(popjtftot);
        popjtftot.setBounds(500, 550, 160, 20);

        popjtfqty.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popjtfqty.setBorder(null);
        popjtfqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popjtfqtyActionPerformed(evt);
            }
        });
        popjtfqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                popjtfqtyKeyReleased(evt);
            }
        });
        popupjual.add(popjtfqty);
        popjtfqty.setBounds(170, 550, 160, 20);

        popjend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png"))); // NOI18N
        popjend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popjendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popjendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popjendMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popjendMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popjendMouseReleased(evt);
            }
        });
        popupjual.add(popjend);
        popjend.setBounds(700, 540, 160, 40);

        popjtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png"))); // NOI18N
        popjtambahbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popjtambahbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popjtambahbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popjtambahbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popjtambahbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popjtambahbarMouseReleased(evt);
            }
        });
        popupjual.add(popjtambahbar);
        popjtambahbar.setBounds(700, 480, 160, 50);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Total Harga");
        popupjual.add(jLabel1);
        jLabel1.setBounds(490, 520, 100, 20);

        popjtfnamabar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popupjual.add(popjtfnamabar);
        popjtfnamabar.setBounds(260, 490, 200, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tf kecil.png"))); // NOI18N
        popupjual.add(jLabel3);
        jLabel3.setBounds(490, 540, 180, 40);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Kuantitas");
        popupjual.add(jLabel4);
        jLabel4.setBounds(160, 520, 100, 20);

        popjtfsat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popjtfsat.setText("Satuan");
        popupjual.add(popjtfsat);
        popjtfsat.setBounds(350, 550, 130, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tf kecil.png"))); // NOI18N
        popupjual.add(jLabel5);
        jLabel5.setBounds(160, 540, 180, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Nama Barang : ");
        popupjual.add(jLabel6);
        jLabel6.setBounds(160, 490, 100, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/bgpop.png"))); // NOI18N
        popupjual.add(jLabel2);
        jLabel2.setBounds(110, 10, 810, 600);

        getContentPane().add(popupjual);
        popupjual.setBounds(246, 100, 1040, 620);

        checkout.setBackground(new java.awt.Color(255, 255, 255));
        checkout.setMinimumSize(new java.awt.Dimension(1280, 720));
        checkout.setLayout(null);

        co_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        co_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                co_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(co_table);

        checkout.add(jScrollPane5);
        jScrollPane5.setBounds(270, 200, 950, 240);

        co_isilblkiri.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        co_isilblkiri.setForeground(new java.awt.Color(48, 56, 65));
        co_isilblkiri.setBorder(null);
        co_isilblkiri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                co_isilblkiriKeyReleased(evt);
            }
        });
        checkout.add(co_isilblkiri);
        co_isilblkiri.setBounds(290, 630, 580, 25);

        ta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ta2.setForeground(new java.awt.Color(48, 56, 65));
        ta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta2.setText("Kode Transaksi :");
        checkout.add(ta2);
        ta2.setBounds(260, 117, 110, 50);

        co_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/print.png"))); // NOI18N
        co_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                co_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                co_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                co_printMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                co_printMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                co_printMouseReleased(evt);
            }
        });
        checkout.add(co_print);
        co_print.setBounds(990, 560, 210, 60);

        co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png"))); // NOI18N
        co_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                co_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                co_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                co_backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                co_backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                co_backMouseReleased(evt);
            }
        });
        checkout.add(co_back);
        co_back.setBounds(990, 620, 210, 60);

        co_kdtrans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        co_kdtrans.setForeground(new java.awt.Color(48, 56, 65));
        co_kdtrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        co_kdtrans.setText("September");
        checkout.add(co_kdtrans);
        co_kdtrans.setBounds(370, 117, 170, 50);

        co_isilblkanan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        co_isilblkanan.setForeground(new java.awt.Color(48, 56, 65));
        co_isilblkanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkout.add(co_isilblkanan);
        co_isilblkanan.setBounds(960, 510, 250, 50);

        co_lblgtot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        co_lblgtot.setForeground(new java.awt.Color(48, 56, 65));
        checkout.add(co_lblgtot);
        co_lblgtot.setBounds(290, 520, 580, 50);

        co_tgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        co_tgl.setForeground(new java.awt.Color(48, 56, 65));
        co_tgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        co_tgl.setText("September");
        checkout.add(co_tgl);
        co_tgl.setBounds(990, 120, 230, 50);

        jualatas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/checkout.png"))); // NOI18N
        checkout.add(jualatas1);
        jualatas1.setBounds(252, 110, 990, 590);

        getContentPane().add(checkout);
        checkout.setBounds(0, 0, 1280, 720);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        tablejual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablejual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablejualMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablejual);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 200, 530, 450);

        jgatot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jgatot.setForeground(new java.awt.Color(48, 56, 65));
        jgatot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jgatot);
        jgatot.setBounds(550, 650, 240, 40);

        jtfqty.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfqty.setForeground(new java.awt.Color(48, 56, 65));
        jtfqty.setBorder(null);
        jtfqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfqtyKeyReleased(evt);
            }
        });
        jPanel1.add(jtfqty);
        jtfqty.setBounds(850, 480, 160, 20);

        jtfharga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfharga.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(jtfharga);
        jtfharga.setBounds(850, 415, 360, 25);

        jtfsatuan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfsatuan.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(jtfsatuan);
        jtfsatuan.setBounds(1050, 480, 150, 20);

        ta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ta1.setForeground(new java.awt.Color(48, 56, 65));
        ta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ta1.setText("Grand Total :");
        jPanel1.add(ta1);
        ta1.setBounds(280, 650, 140, 40);

        jtftotal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtftotal.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(jtftotal);
        jtftotal.setBounds(850, 543, 360, 20);

        jtfnamabar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfnamabar.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(jtfnamabar);
        jtfnamabar.setBounds(850, 355, 360, 25);

        jtfkdbar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfkdbar.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(jtfkdbar);
        jtfkdbar.setBounds(850, 300, 160, 27);

        jtfkdbat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jtfkdbat.setForeground(new java.awt.Color(48, 56, 65));
        jtfkdbat.setBorder(null);
        jtfkdbat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfkdbatActionPerformed(evt);
            }
        });
        jtfkdbat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfkdbatKeyReleased(evt);
            }
        });
        jPanel1.add(jtfkdbat);
        jtfkdbat.setBounds(1050, 300, 160, 23);

        jeditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png"))); // NOI18N
        jeditbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jeditbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jeditbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jeditbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jeditbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jeditbarMouseReleased(evt);
            }
        });
        jPanel1.add(jeditbar);
        jeditbar.setBounds(840, 580, 190, 40);

        jhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png"))); // NOI18N
        jhpsbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhpsbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jhpsbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jhpsbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jhpsbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jhpsbarMouseReleased(evt);
            }
        });
        jPanel1.add(jhpsbar);
        jhpsbar.setBounds(1040, 580, 190, 40);

        jcheckout.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png"))); // NOI18N
        jcheckout.setAlignmentX(0.5F);
        jcheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcheckoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcheckoutMouseReleased(evt);
            }
        });
        jPanel1.add(jcheckout);
        jcheckout.setBounds(840, 640, 380, 40);

        ta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ta.setForeground(new java.awt.Color(48, 56, 65));
        ta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta.setText("Kode Transaksi :");
        jPanel1.add(ta);
        ta.setBounds(260, 117, 110, 50);

        jkdtrans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jkdtrans.setForeground(new java.awt.Color(48, 56, 65));
        jkdtrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkdtrans.setText("September");
        jPanel1.add(jkdtrans);
        jkdtrans.setBounds(370, 117, 170, 50);

        jcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png"))); // NOI18N
        jcaribar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcaribarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcaribarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcaribarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcaribarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcaribarMouseReleased(evt);
            }
        });
        jPanel1.add(jcaribar);
        jcaribar.setBounds(840, 200, 390, 40);

        jtgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtgl.setForeground(new java.awt.Color(48, 56, 65));
        jtgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jtgl.setText("September");
        jPanel1.add(jtgl);
        jtgl.setBounds(990, 120, 230, 50);

        jualatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/bgtrans.png"))); // NOI18N
        jPanel1.add(jualatas);
        jualatas.setBounds(252, 110, 990, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfkdbatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfkdbatKeyReleased
        // TODO add your handling code here:
if (jtfkdbat.getText().equals("")) {
} else {
    try {
            String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan " +
                    "WHERE barcode = '" + jtfkdbat.getText() + "' ;";
            Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            res.next() ;
                jtfkdbar.setText(res.getString(1));
                        jtfnamabar.setText(res.getString(2));
                        jtfharga.setText(String.valueOf(res.getInt(3)));
                        jtfsatuan.setText(res.getString(4));
                        jtfqty.setText("1");

                double qty = Double.parseDouble(jtfqty.getText()), hrg = Double.parseDouble(jtfharga.getText());
                Double tot = hrg * qty;
                jtftotal.setText(String.valueOf(tot));
        } catch (Exception e) {

        }
}
    }//GEN-LAST:event_jtfkdbatKeyReleased

    private void jcaribarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcaribarMouseClicked
        // TODO add your handling code here:
//popjualcari.set
popupjual.setVisible(true);
popupjual.requestFocus();
jPanel1.setVisible(false);

popjualcari.setForeground(new java.awt.Color(221,221,221));
popjualcari.setText("Cari Nama Barang");
settablepopjual();
    }//GEN-LAST:event_jcaribarMouseClicked

    private void popjtfqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popjtfqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popjtfqtyActionPerformed

    private void popjtftotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popjtftotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popjtftotActionPerformed

    private void popjualcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popjualcariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_popjualcariActionPerformed

    private void popjendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjendMouseClicked
        // TODO add your handling code here:
popupjual.setVisible(false);
popupjual.requestFocus();
jPanel1.setVisible(true);
    }//GEN-LAST:event_popjendMouseClicked

    private void popjualcariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popjualcariFocusLost
        // TODO add your handling code here:
if (popjualcari.getText().equals("")) {
popjualcari.setForeground(new java.awt.Color(221,221,221));
popjualcari.setText("Cari Nama Barang");
} else {
}
    }//GEN-LAST:event_popjualcariFocusLost

    private void popjualcariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popjualcariFocusGained
        // TODO add your handling code here:
if (popjualcari.getText().equals("Cari Nama Barang")) {
popjualcari.setForeground(new java.awt.Color(51,51,51));
popjualcari.setText("");
} else {
}
    }//GEN-LAST:event_popjualcariFocusGained

    private void popjtfqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popjtfqtyKeyReleased
        // TODO add your handling code here:
        if (popjtfnamabar.getText().equals("")) {
                    panggilAlertMerah("Gagal !", "Pilih dulu barang dari table");
        } else {
            double qty = Double.parseDouble(popjtfqty.getText());
            Double tot = popharga * qty;
            popjtftot.setText(String.valueOf(tot));
        }
    }//GEN-LAST:event_popjtfqtyKeyReleased

    private void popjtambahbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjtambahbarMouseClicked
        // TODO add your handling code here:
        if (popjtfnamabar.getText().equals("")) {
            panggilAlertMerah("Tambah Gagal !", "Pilih dahulu barang dari Table");
        } else {
        Double qty = null, cartqty = 0.0;
        String bar = "";
        try {
            String sqll = "SELECT jumlah FROM barang where id_barang='" + jkdbar + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            qty = res.getDouble(1);
        } catch (Exception e) {
        }
        try {
            String sqll = "SELECT qty FROM cart_penjualan where id_barang='" + jkdbar + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            cartqty = res.getDouble(1);
        } catch (Exception e) {
        }
            if (qty < (cartqty+Double.parseDouble(popjtfqty.getText()))) {
                panggilAlertMerah("Tambah Gagal !", "Kuantitas melebihi stok");
            } else {

                try {
                    String sqll = "SELECT id_barang FROM cart_penjualan where id_barang='" + jkdbar + "' ;";
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.Statement stm = conn.createStatement();
                    java.sql.ResultSet res = stm.executeQuery(sqll);
                    res.next();
                    bar = res.getString("id_barang");
                } catch (Exception e) {
                }
                if (bar.equals(jkdbar)) {
               AlertPertanyaanHijau obj = new AlertPertanyaanHijau(this);
               obj.showMessage("Konfirmasi Tambah Barang", "Barang sudah ada dalam keranjang! \nApakah anda ingin menambahkan kuantitasnya saja? ");
               if (obj.getMessageType() == AlertPertanyaanHijau.MessageType.OK){
            
            try {
                            String sqll = "UPDATE cart_penjualan "
                                    + "SET harga = " + popharga
                                    + ", qty = qty+" + popjtfqty.getText()
                                    + ", harga_total = harga_total+" + popjtftot.getText()
                                    + " WHERE cart_penjualan.id_barang = '" + jkdbar + "'";
                            java.sql.Connection conn = (Connection) Config.configDB();
                            java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                            pstl.execute();
                            popjkosong();
                            settablejual();
                            popupjual.setVisible(false);
                            jPanel1.setVisible(true);
                        } catch (Exception e) {
                            panggilAlertMerah("Tambah Gagal !", "Data Gagal Disimpan");
                        }
                    } else if (obj.getMessageType() == AlertPertanyaanHijau.MessageType.CANCEL) {
            
        }
                } else {
                    try {
                        String sqll = "INSERT INTO `cart_penjualan` (`id_penjualan`, `id_barang`, `harga`, `qty`, `harga_total`)" +
                                " VALUES ('" + jkdtrans.getText() + "', '"
                                + jkdbar + "', '"
                                +  popharga + "', '"
                                + popjtfqty.getText() + "', '"
                                + popjtftot.getText() + "'); ";
                        java.sql.Connection conn = (Connection) Config.configDB();
                        java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                        pstl.execute();
                        popjkosong();
                        settablejual();
                        popupjual.setVisible(false);
                        jPanel1.setVisible(true);
                    } catch (Exception e) {
                        panggilAlertMerah("Tambah Gagal !", "Data Gagal Disimpan");
                    }
                }

            }
        }
    }//GEN-LAST:event_popjtambahbarMouseClicked

    private void jhpsbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhpsbarMouseClicked
        // TODO add your handling code here:
    if (jtfkdbar.getText().equals("")) {
            panggilAlertMerah("Hapus Gagal !", "Pilih dahulu barang dari Table");
        } else {
               AlertPertanyaan obj = new AlertPertanyaan(this);
               obj.showMessage("Konfirmasi Hapus Barang", "apakah anda yakin ingin menghapus barang dengan Kode " + jtfkdbar.getText() + " dari keranjang ?");
               if (obj.getMessageType() == AlertPertanyaan.MessageType.OK){
                try {
                    String sql = "DELETE FROM cart_penjualan where id_barang='" + jtfkdbar.getText() + "'";
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    settablejual();
                    jkosong();
                } catch (Exception e) {
                    panggilAlertMerah("Hapus Gagal !", "penghapusan data penjualan barang gagal");
                }
            }
        }
    }//GEN-LAST:event_jhpsbarMouseClicked

    private void jcheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckoutMouseClicked
        // TODO add your handling code here:
        DefaultTableModel cartmodel = (DefaultTableModel) tablejual.getModel();
        if (cartmodel.getRowCount ()==0) {
            panggilAlertMerah("Checkout Gagal !", "Keranjang masih kosong");
        } else {
                AlertPertanyaanHijau obj = new AlertPertanyaanHijau(this);
               obj.showMessage("Konfirmasi Checkout", "apakah anda yakin untuk checkout ?");
               if (obj.getMessageType() == AlertPertanyaanHijau.MessageType.OK){
            jcheckout();
            jkosong();
            mainco();
        }
    }
    }//GEN-LAST:event_jcheckoutMouseClicked

    private void popjualcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popjualcariKeyReleased
        // TODO add your handling code here:
tablepopjual.fixTable(jScrollPane4);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    
    try {
        int no=1;
        String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, barang.jumlah, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan "
                    + "WHERE nama_barang like '%" + popjualcari.getText() + "%' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5)
            });
        }
        tablepopjual.setModel(model);
    } catch (Exception e) {
        String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
    }
    }//GEN-LAST:event_popjualcariKeyReleased

    private void co_isilblkiriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_co_isilblkiriKeyReleased
        // TODO add your handling code here:
        if (co_isilblkiri.getText().equals("")) {

        } else {
            String total = co_lblgtot.getText();
            total = total.replace("Rp. ", "");
            int ttl = Integer.parseInt(total), uang = Integer.parseInt(co_isilblkiri.getText());
            int kembalian = uang - ttl;
            co_isilblkanan.setText("Rp. " + kembalian);
        }
    }//GEN-LAST:event_co_isilblkiriKeyReleased

    private void co_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseClicked
        // TODO add your handling code here:
            settablejual();
            setJkdtrans();
            checkout.setVisible(false);
            jPanel1.setVisible(true);
            setJtgl();
    }//GEN-LAST:event_co_backMouseClicked

    private void co_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_printMouseClicked
        // TODO add your handling code here:
        String balik = co_isilblkanan.getText();
        balik = balik.replace("Rp. ", "");
        try {
            String sqll = "UPDATE penjualan "
                    + "SET uang = '" + co_isilblkiri.getText()
                    + "', kembalian = '" +balik
                    + "' WHERE penjualan.id_penjualan = '" + jkdtrans.getText() + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
            pstl.execute();
        try {
//            java.sql.Connection conn=(com.mysql.jdbc.Connection)Config.configDB();
//        String namafile = "src/kasir/report.jrxml";
            InputStream report = getClass().getResourceAsStream("jual.jasper");
            HashMap param = new HashMap();
            param.put("kd_trans", co_kdtrans.getText());
//        File file = new File(namafile);
//        JasperDesign jd = JRXmlLoader.load(namafile);
//        JasperReport jr = JasperCompileManager.compileReport(jd);
//            String reportPath = report;
//            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(report,param,conn);
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            e.printStackTrace();
            String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
        }
        } catch (Exception e) {
                    panggilAlertMerah("Print Gagal !", "Masukkan jumlah yang benar pada bayar");
        }


    }//GEN-LAST:event_co_printMouseClicked

    private void jtfkdbatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfkdbatActionPerformed
        // TODO add your handling code here:
if (jtfkdbat.getText().equals("")) {
} else {
        Double qty = null, cartqty = 0.0;
        String bar = "", kd = jtfkdbar.getText();
        try {
            String sqll = "SELECT jumlah FROM barang where id_barang='" + kd + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            qty = res.getDouble(1);
        } catch (Exception e) {
        }
        try {
            String sqll = "SELECT qty FROM cart_penjualan where id_barang='" + kd + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            cartqty = res.getDouble(1);
        } catch (Exception e) {
        }
if (qty < (cartqty+1)) {
                panggilAlertMerah("Gagal !", "Kuantitas melebihi stok");
} else {
        try {
            String sqll = "SELECT id_barang FROM cart_penjualan where id_barang='" + kd + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            bar = res.getString("id_barang");
        } catch (Exception e) {
        }
        if (bar.equals(kd)) {
                try {
                    String sqll = "UPDATE cart_penjualan "
                            + "SET qty = qty+" + jtfqty.getText()
                            + ", harga_total = harga_total+" + jtftotal.getText()
                            + " WHERE cart_penjualan.id_barang = '" + kd + "'";
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                    pstl.execute();
                    jkosong();
                    settablejual();
                } catch (Exception e) {
                    String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
                }
        } else {
            try {
                String sqll = "INSERT INTO `cart_penjualan` (`id_penjualan`, `id_barang`, `harga`, `qty`, `harga_total`)" +
                        " VALUES ('" + jkdtrans.getText() + "', '"
                        + kd + "', '"
                        + jtfharga.getText() + "', '"
                        + jtfqty.getText() + "', '"
                        + jtftotal.getText() + "'); ";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                pstl.execute();
                jkosong();
                settablejual();
            } catch (Exception e) {
                String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
            }
        }
}
}
    }//GEN-LAST:event_jtfkdbatActionPerformed

    private void tablepopjualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepopjualMouseClicked
        // TODO add your handling code here:
        int baris = tablepopjual.rowAtPoint(evt.getPoint());
        jkdbar = tablepopjual.getValueAt(baris, 0).toString();
        if (tablepopjual.getValueAt(baris, 1)==null) {
            popjtfnamabar.setText("");
        } else {
            popjtfnamabar.setText(tablepopjual.getValueAt(baris, 1).toString());
        }
        if (tablepopjual.getValueAt(baris, 2)==null) {
            popharga = 0;
        } else {
            String harga = tablepopjual.getValueAt(baris, 2).toString();
            popharga = Integer.parseInt(harga);
        }
        if (tablepopjual.getValueAt(baris, 3)==null) {
            popqty = 0.0;
        } else {
            String qty = tablepopjual.getValueAt(baris, 3).toString();
            popqty = Double.parseDouble(qty);
        }
        if (tablepopjual.getValueAt(baris, 4)==null) {
            
        } else {
            popjtfsat.setText(tablepopjual.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tablepopjualMouseClicked

    private void tablejualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablejualMouseClicked
        // TODO add your handling code here:
int baris = tablejual.rowAtPoint(evt.getPoint());
        jtfkdbar.setText(tablejual.getValueAt(baris, 0).toString());
        try {
            String sql = "select barcode from barang " +
                    "WHERE id_barang = '" + tablejual.getValueAt(baris, 0).toString() + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            jtfkdbat.setText(rs.getString("barcode"));

        } catch (Exception e) {
            e.printStackTrace();
        }
        if (tablejual.getValueAt(baris, 1)==null) {
            jtfnamabar.setText("");
        } else {
            jtfnamabar.setText(tablejual.getValueAt(baris, 1).toString());
        }
        if (tablejual.getValueAt(baris, 2)==null) {
            jtfharga.setText("");
        } else {
            jtfharga.setText(tablejual.getValueAt(baris, 2).toString());
        }
        if (tablejual.getValueAt(baris, 3)==null) {
            jtfqty.setText("");
        } else {
            jtfqty.setText(tablejual.getValueAt(baris, 3).toString());  
        }
        if (tablejual.getValueAt(baris, 5)==null) {
            jtftotal.setText("");
        } else {
            jtftotal.setText(tablejual.getValueAt(baris, 5).toString());
        }
        if (tablejual.getValueAt(baris, 4)==null) {
            jtfsatuan.setText("");
        } else {
            String sat= tablejual.getValueAt(baris, 4).toString();
        try {
            String sql = "SELECT satuan from satuan "
                    + "where id_satuan = '" + sat + "';";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            jtfsatuan.setText(rs.getString("satuan"));

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_tablejualMouseClicked

    private void gudangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseEntered
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang-hover.png")));
    }//GEN-LAST:event_gudangMouseEntered

    private void gudangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseExited
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png")));
    }//GEN-LAST:event_gudangMouseExited

    private void gudangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMousePressed
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang-clicked.png")));
    }//GEN-LAST:event_gudangMousePressed

    private void gudangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseReleased
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png")));
    }//GEN-LAST:event_gudangMouseReleased

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        TransaksiJualkar Transaksijual = new TransaksiJualkar();
        Transaksijual.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksiMouseClicked

    private void transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseEntered

    private void transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseExited

    private void transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMousePressed

    private void transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseReleased

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png")));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png")));
    }//GEN-LAST:event_dashboardMouseExited

    private void dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMousePressed
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard-clicked.png")));
    }//GEN-LAST:event_dashboardMousePressed

    private void dashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseReleased
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png")));
    }//GEN-LAST:event_dashboardMouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout-hover.png")));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout-hover.png")));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png")));
    }//GEN-LAST:event_logoutMouseReleased

    private void pengaturanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseEntered
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan-hover.png")));
    }//GEN-LAST:event_pengaturanMouseEntered

    private void pengaturanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseExited
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png")));
    }//GEN-LAST:event_pengaturanMouseExited

    private void pengaturanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMousePressed
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan-clicked.png")));
    }//GEN-LAST:event_pengaturanMousePressed

    private void pengaturanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseReleased
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png")));
    }//GEN-LAST:event_pengaturanMouseReleased

    private void riwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseEntered
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat-hover.png")));
    }//GEN-LAST:event_riwayatMouseEntered

    private void riwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseExited
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png")));
    }//GEN-LAST:event_riwayatMouseExited

    private void riwayatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMousePressed
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat-clicked.png")));
    }//GEN-LAST:event_riwayatMousePressed

    private void riwayatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseReleased
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png")));
    }//GEN-LAST:event_riwayatMouseReleased

    private void jeditbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditbarMouseClicked
        // TODO add your handling code here:
if (jtfkdbar.getText().equals("")) {
                    panggilAlertMerah("Edit Gagal !", "Pilih dahulu barang yang ingin diedit!");
        } else {
Double qty = null, cartqty = Double.parseDouble(jtfqty.getText());
        String bar = "", kd = jtfkdbar.getText();
        try {
            String sqll = "SELECT jumlah FROM barang where id_barang='" + kd + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sqll);
            res.next();
            qty = res.getDouble(1);
        } catch (Exception e) {
        }
if (qty < cartqty) {
                panggilAlertMerah("Edit Gagal !", "Kuantitas Melebihi Stok");
} else {
            try {
                String sqll = "UPDATE cart_penjualan "
                        + "SET qty = '" + jtfqty.getText()
                        + "', harga_total = '" + jtftotal.getText()
                        + "' WHERE cart_penjualan.id_barang = '" + jtfkdbar.getText() + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                pstl.execute();
            jkosong();
            settablejual();
            } catch (Exception e) {
                String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
            }
        }
}
    }//GEN-LAST:event_jeditbarMouseClicked

    private void jtfqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfqtyKeyReleased
        // TODO add your handling code here:
if (jtfkdbar.getText().equals("")) {
        } else {
            double qty = Double.parseDouble(jtfqty.getText()), hrg = Double.parseDouble(jtfharga.getText());
            Double tot = hrg * qty;
            jtftotal.setText(String.valueOf(tot));
        }
    }//GEN-LAST:event_jtfqtyKeyReleased

    private void co_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_co_tableMouseClicked

    private void popjtambahbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjtambahbarMouseEntered
        // TODO add your handling code here:
popjtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah-hover.png")));
    }//GEN-LAST:event_popjtambahbarMouseEntered

    private void popjtambahbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjtambahbarMouseExited
        // TODO add your handling code here:
popjtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png")));
    }//GEN-LAST:event_popjtambahbarMouseExited

    private void popjtambahbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjtambahbarMousePressed
        // TODO add your handling code here:
popjtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah-clicked.png")));
    }//GEN-LAST:event_popjtambahbarMousePressed

    private void popjtambahbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjtambahbarMouseReleased
        // TODO add your handling code here:
popjtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png")));
    }//GEN-LAST:event_popjtambahbarMouseReleased

    private void popjendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjendMouseEntered
        // TODO add your handling code here:
popjend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali-hover.png")));
    }//GEN-LAST:event_popjendMouseEntered

    private void popjendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjendMouseExited
        // TODO add your handling code here:
popjend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png")));
    }//GEN-LAST:event_popjendMouseExited

    private void popjendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjendMousePressed
        // TODO add your handling code here:
popjend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali-clicked.png")));
    }//GEN-LAST:event_popjendMousePressed

    private void popjendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popjendMouseReleased
        // TODO add your handling code here:
popjend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png")));
    }//GEN-LAST:event_popjendMouseReleased

    private void jcaribarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcaribarMouseEntered
        // TODO add your handling code here:
jcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang-hover.png")));
    }//GEN-LAST:event_jcaribarMouseEntered

    private void jcaribarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcaribarMouseExited
        // TODO add your handling code here:
jcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png")));
    }//GEN-LAST:event_jcaribarMouseExited

    private void jcaribarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcaribarMousePressed
        // TODO add your handling code here:
jcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang-clicked.png")));
    }//GEN-LAST:event_jcaribarMousePressed

    private void jcaribarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcaribarMouseReleased
        // TODO add your handling code here:
jcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png")));
    }//GEN-LAST:event_jcaribarMouseReleased

    private void jeditbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditbarMouseEntered
        // TODO add your handling code here:
jeditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang-hover.png")));
    }//GEN-LAST:event_jeditbarMouseEntered

    private void jeditbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditbarMouseExited
        // TODO add your handling code here:
jeditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png")));
    }//GEN-LAST:event_jeditbarMouseExited

    private void jeditbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditbarMousePressed
        // TODO add your handling code here:
jeditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang-clicked.png")));
    }//GEN-LAST:event_jeditbarMousePressed

    private void jeditbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditbarMouseReleased
        // TODO add your handling code here:
jeditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png")));
    }//GEN-LAST:event_jeditbarMouseReleased

    private void jhpsbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhpsbarMouseEntered
        // TODO add your handling code here:
jhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang-hover.png")));
    }//GEN-LAST:event_jhpsbarMouseEntered

    private void jhpsbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhpsbarMouseExited
        // TODO add your handling code here:
jhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png")));
    }//GEN-LAST:event_jhpsbarMouseExited

    private void jhpsbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhpsbarMousePressed
        // TODO add your handling code here:
jhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang-clicked.png")));
    }//GEN-LAST:event_jhpsbarMousePressed

    private void jhpsbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhpsbarMouseReleased
        // TODO add your handling code here:
jhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png")));
    }//GEN-LAST:event_jhpsbarMouseReleased

    private void jcheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckoutMouseEntered
        // TODO add your handling code here:
jcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout-hover.png")));
    }//GEN-LAST:event_jcheckoutMouseEntered

    private void jcheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckoutMouseExited
        // TODO add your handling code here:
jcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png")));
    }//GEN-LAST:event_jcheckoutMouseExited

    private void jcheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckoutMousePressed
        // TODO add your handling code here:
jcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout-clicked.png")));
    }//GEN-LAST:event_jcheckoutMousePressed

    private void jcheckoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckoutMouseReleased
        // TODO add your handling code here:
jcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png")));
    }//GEN-LAST:event_jcheckoutMouseReleased

    private void co_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_printMouseEntered
        // TODO add your handling code here:
co_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/print-hover.png")));
    }//GEN-LAST:event_co_printMouseEntered

    private void co_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_printMouseExited
        // TODO add your handling code here:
co_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/print.png")));
    }//GEN-LAST:event_co_printMouseExited

    private void co_printMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_printMousePressed
        // TODO add your handling code here:
co_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/print-clicked.png")));
    }//GEN-LAST:event_co_printMousePressed

    private void co_printMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_printMouseReleased
        // TODO add your handling code here:
co_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/print.png")));
    }//GEN-LAST:event_co_printMouseReleased

    private void co_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseEntered
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali-hover.png")));
    }//GEN-LAST:event_co_backMouseEntered

    private void co_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseExited
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png")));
    }//GEN-LAST:event_co_backMouseExited

    private void co_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMousePressed
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali-clicked.png")));
    }//GEN-LAST:event_co_backMousePressed

    private void co_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseReleased
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png")));
    }//GEN-LAST:event_co_backMouseReleased

    private void namaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_namaAncestorAdded
        // TODO add your handling code here:
        setprofile();
    }//GEN-LAST:event_namaAncestorAdded

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
Dashboardkar dashboardkar = new Dashboardkar();
dashboardkar.nama.setText(nama.getText());
dashboardkar.setVisible(true);
this.dispose();

    }//GEN-LAST:event_dashboardMouseClicked

    private void gudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseClicked
        // TODO add your handling code here:
                    Gudangkar gudangkar = new Gudangkar();
                    gudangkar.nama.setText(nama.getText());
                    gudangkar.setVisible(true);
                    this.dispose();

    }//GEN-LAST:event_gudangMouseClicked

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        // TODO add your handling code here:
RiwayatJualkar riwayatjualkar = new RiwayatJualkar();
riwayatjualkar.nama.setText(nama.getText());
riwayatjualkar.setVisible(true);
this.dispose();

    }//GEN-LAST:event_riwayatMouseClicked

    private void pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseClicked
                    Setting setting = new Setting();
                    setting.nama.setText(nama.getText());
                    setting.setVisible(true);
                    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_pengaturanMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        AlertPertanyaan obj = new AlertPertanyaan(this);
        obj.showMessage("Logout !", "Apakah Anda Ingin Logout ?");
        if (obj.getMessageType() == AlertPertanyaan.MessageType.OK) {
            Login login = new Login();
login.setVisible(true);
this.dispose();
        } else {
            
        }

    }//GEN-LAST:event_logoutMouseClicked

    void jcheckout() {
        try {
            String sqll = "insert into penjualan (id_penjualan, tanggal_transaksi, jam_transaksi, "
                    + "total_bayar, uang, kembalian, id_pengguna) " +
                    "values ('" + jkdtrans.getText() + "', CURRENT_DATE, CURRENT_TIME, 0, 0, 0, "
                    + "'"+nama.getText()+"') ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
            pstl.execute();
            String sql = "insert into detail_penjualan (`id_penjualan`, `id_barang`, "
                    + " `harga`, `qty`, `harga_total`) "
                    + "SELECT id_penjualan, id_barang, harga, qty, harga_total FROM cart_penjualan ;";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Checkout Gagal !", c);
        }
        try {
            String sql = "TRUNCATE TABLE cart_penjualan;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
        }
}

    void setJkdtrans() {
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyy-");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        DateTimeFormatter dtff = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime tanggall = LocalDateTime.now();
        String aa = (dtff.format(tanggall));
        try {
            //--> melakukan eksekusi query untuk mengambil data dari tabel
            String sql = "SELECT MAX(id_penjualan) FROM penjualan " +
                    "WHERE tanggal_transaksi = '" + aa + "' ;" ;
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString(1) == null) {
                    jkdtrans.setText("TR-" + a + "001");
                } else {
                    rs.last();
                    String auto = rs.getString(1);
                    auto = auto.replace("TR-" + a, "");
                    int auto_id = Integer.parseInt(auto) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 3 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    jkdtrans.setText("TR-" + a + no);
                }
            }
            rs.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setJtgl() {
        String mm = "";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        DateTimeFormatter dtff = DateTimeFormatter.ofPattern("dd");
        LocalDateTime tanggall = LocalDateTime.now();
        String aa = (dtff.format(tanggall));
        DateTimeFormatter dtfff = DateTimeFormatter.ofPattern("yyyy");
        LocalDateTime tanggalll = LocalDateTime.now();
        String yyyy = (dtfff.format(tanggalll));
        int b = Integer.parseInt(a);
        switch (b) {
            case 1:
                mm = ("Januari");
                break;
            case 2:
                mm = ("Februari");
                break;
            case 3:
                mm = ("Maret");
                break;
            case 4:
                mm = ("April");
                break;
            case 5:
                mm = ("Mei");
                break;
            case 6:
                mm = ("Juni");
                break;
            case 7:
                mm = ("Juli");
                break;
            case 8:
                mm = ("Agustus");
                break;
            case 9:
                mm = ("September");
                break;
            case 10:
                mm = ("Oktober");
                break;
            case 11:
                mm = ("November");
                break;
            case 12:
                mm = ("Desember");
                break;
        }
        jtgl.setText(aa + " " + mm + " " + yyyy);
    }

    void cekcartjual() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyy-");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        try {
            //--> melakukan eksekusi query untuk mengambil data dari tabel
            String sql = "SELECT MAX(id_penjualan) FROM cart_penjualan " +
                    "WHERE id_penjualan like '%" + a + "%' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString(1) == null) {
                    try {
                        String sqll = "TRUNCATE TABLE cart_penjualan;";
                        java.sql.Connection connn = (Connection) Config.configDB();
                        java.sql.PreparedStatement pstl = connn.prepareStatement(sqll);
                        pstl.execute();
                    } catch (Exception e) {
                    }
                } else {
//                    System.out.println("kosong");
                }
            }
            rs.close();
        } catch(Exception e){
            e.printStackTrace();
        }

    }

    void settablejual() {
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);

    tablejual.fixTable(jScrollPane2);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode");
    model.addColumn("Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    model.addColumn("Total");
    
    try {
        int no=1;
        String sql = "select cart_penjualan.id_barang, barang.nama_barang, barang.harga_jual, " +
                    "cart_penjualan.qty, barang.id_satuan, cart_penjualan.harga_total " +
                    "from cart_penjualan join barang on cart_penjualan.id_barang = barang.id_barang"
                    + " where id_penjualan = '" + jkdtrans.getText() + "' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getDouble(4),
                res.getString(5),res.getString(6)
            });
        }
        tablejual.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }

    try {
            String sql = "SELECT sum(harga_total) as total from cart_penjualan "
                    + "where id_penjualan = '"+jkdtrans.getText()+"' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
                jgatot.setText("Rp. "+rs.getInt("total"));

        } catch (SQLException e) {
            e.printStackTrace();
        }

}

public final void settablepopjual() {
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);
tablepopjual.fixTable(jScrollPane4);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    
    try {
        int no=1;
        String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, barang.jumlah, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5)
            });
        }
        tablepopjual.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    void jkosong() {
        jtfkdbar.setText("");
        jtfkdbat.setText("");
        jtfnamabar.setText(null);
        jtfharga.setText(null);
        jtfqty.setText(null);
        jtfsatuan.setText(null);
        jtftotal.setText(null);
    }

   void popjkosong() {
        popjtfnamabar.setText("");
        popjtfqty.setText(null);
        popjtfsat.setText(null);
        popjtftot.setText(null);
    }

    void mainco() {
        co_kdtrans.setText(jkdtrans.getText());
        co_tgl.setText(jtgl.getText());
        checkout.setVisible(true);
        jPanel1.setVisible(false);
        settableco();
        try {
            String sql = "SELECT total_bayar from penjualan" +
                    " WHERE id_penjualan = '" + co_kdtrans.getText() + "' ;";
            Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            res.next();
            co_lblgtot.setText("Rp. " + res.getString(1));
        } catch (SQLException e) {
            e.printStackTrace();
        }
}

    void settableco() {
co_table.fixTable(jScrollPane5);
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    model.addColumn("Harga Total");
    
    try {
        int no=1;
        String sql = "select detail_penjualan.id_barang, barang.nama_barang, " +
                    "detail_penjualan.harga, detail_penjualan.qty, barang.id_satuan, detail_penjualan.harga_total " +
                    "from detail_penjualan join barang on detail_penjualan.id_barang = barang.id_barang"
                    + " where id_penjualan = '" + jkdtrans.getText() + "' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5),res.getString(6)
            });
        }
        co_table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void jcheckoutActionPerformed(java.awt.event.ActionEvent evt) {

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiJualkar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiJualkar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiJualkar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiJualkar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiJualkar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel checkout;
    private javax.swing.JLabel co_back;
    private javax.swing.JLabel co_isilblkanan;
    private javax.swing.JTextField co_isilblkiri;
    private javax.swing.JLabel co_kdtrans;
    private javax.swing.JLabel co_lblgtot;
    private javax.swing.JLabel co_print;
    private tabledark.TableDark co_table;
    private javax.swing.JLabel co_tgl;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel gudang;
    private javax.swing.JLabel h;
    private javax.swing.JLabel header;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jcaribar;
    private javax.swing.JLabel jcheckout;
    private javax.swing.JLabel jeditbar;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel jgatot;
    private javax.swing.JLabel jhpsbar;
    private javax.swing.JLabel jkdtrans;
    private javax.swing.JLabel jtfharga;
    private javax.swing.JLabel jtfkdbar;
    private javax.swing.JTextField jtfkdbat;
    private javax.swing.JLabel jtfnamabar;
    private javax.swing.JTextField jtfqty;
    private javax.swing.JLabel jtfsatuan;
    private javax.swing.JLabel jtftotal;
    private javax.swing.JLabel jtgl;
    private javax.swing.JLabel jualatas;
    private javax.swing.JLabel jualatas1;
    private javax.swing.JLabel logout;
    public javax.swing.JLabel nama;
    private javax.swing.JLabel pengaturan;
    private javax.swing.JLabel popjend;
    private javax.swing.JLabel popjtambahbar;
    private javax.swing.JLabel popjtfnamabar;
    private javax.swing.JTextField popjtfqty;
    private javax.swing.JLabel popjtfsat;
    private javax.swing.JTextField popjtftot;
    private javax.swing.JTextField popjualcari;
    private javax.swing.JPanel popupjual;
    private javax.swing.JLabel riwayat;
    private javax.swing.JLabel ta;
    private javax.swing.JLabel ta1;
    private javax.swing.JLabel ta2;
    private tabledark.TableDark tablejual;
    private tabledark.TableDark tablepopjual;
    private javax.swing.JLabel transaksi;
    // End of variables declaration//GEN-END:variables
}
