/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javaswingdev.message.AlertBerhasil;
import javaswingdev.message.AlertGagal;
import javaswingdev.message.AlertPertanyaan;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author yogan
 */
public class TransaksiBeli extends javax.swing.JFrame {
int popharga;
String jkdbar;
Double popqty;
private ImageIcon format = null;
    /**
     * Creates new form TransaksiJual
     */
    public TransaksiBeli() {
        initComponents();
        btfkdbat.requestFocus();
        setBkdtrans();
        setBtgl();
        setBsup();
        setTablebeli();
        cekcartbeli();
        btfkdbat.requestFocus();
        popupbeli.setVisible(false);
        checkout.setVisible(false);
        jPanel1.setVisible(true);
        Cursor();
        setFavIcon();
        Toolkit toolkit = getToolkit ();
        Dimension size = toolkit.getScreenSize();
        setLocation (size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    void Cursor(){
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        karyawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
        pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
        riwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popbtambahbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));       
        popbend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bswitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcaribar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beditbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhpsbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        co_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btambahbar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

private void setFavIcon(){
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/img/Logoapp.png")));
}

void setprofile() {
        try {
            String sql = "SELECT jenis_pengguna, img"
                    + " FROM pengguna"
                    + " WHERE id_pengguna='" + nama.getText() +"' ;" ;
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            jenis.setText(rs.getString(1));

            String imgsql = rs.getString(2);
//admin
            try{
            BufferedImage img = null;
            img = ImageIO.read(new File(imgsql));
            Image img1=img.getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH);
            format = new ImageIcon(img1);
            image.setIcon(format);
            }catch(Exception e){
            e.printStackTrace();
            }
//} else {
//
//}

        } catch (SQLException e) {
            e.printStackTrace();
        }
}
void panggilAlertHijau(String Title,String message){
            AlertBerhasil obj2 = new AlertBerhasil(this);
            obj2.showMessage(Title, message);
}
void panggilAlertMerah(String Title, String message){
            AlertGagal obj3 = new AlertGagal(this);
            obj3.showMessage(Title, message);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenis = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        karyawan = new javax.swing.JLabel();
        retur = new javax.swing.JLabel();
        gudang = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        pengaturan = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebeli = new tabledark.TableDark();
        bsup = new combo_suggestion.ComboBoxSuggestion();
        bgatot = new javax.swing.JLabel();
        btfharga = new javax.swing.JTextField();
        btfqty = new javax.swing.JTextField();
        btfsatuan = new javax.swing.JLabel();
        ta1 = new javax.swing.JLabel();
        btftotal = new javax.swing.JLabel();
        btfnamabar = new javax.swing.JLabel();
        btfkdbar = new javax.swing.JLabel();
        btfkdbat = new javax.swing.JTextField();
        btambahbar = new javax.swing.JLabel();
        bhpsbar = new javax.swing.JLabel();
        beditbar = new javax.swing.JLabel();
        bcheckout = new javax.swing.JLabel();
        ta = new javax.swing.JLabel();
        bkdtrans = new javax.swing.JLabel();
        bcaribar = new javax.swing.JLabel();
        btgl = new javax.swing.JLabel();
        bswitch = new javax.swing.JLabel();
        jualatas = new javax.swing.JLabel();
        checkout = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        co_table = new tabledark.TableDark();
        co_isilblkiri = new javax.swing.JLabel();
        ta2 = new javax.swing.JLabel();
        co_back = new javax.swing.JLabel();
        co_kdtrans = new javax.swing.JLabel();
        co_isilblkanan = new javax.swing.JLabel();
        co_lblgtot = new javax.swing.JLabel();
        co_tgl = new javax.swing.JLabel();
        jualatas1 = new javax.swing.JLabel();
        popupbeli = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablepopbeli = new tabledark.TableDark();
        popbelicari = new javax.swing.JTextField();
        h = new javax.swing.JLabel();
        popbend = new javax.swing.JLabel();
        popbtambahbar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko-Berkah Transaksi Beli");
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        jenis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jenis.setForeground(new java.awt.Color(48, 56, 65));
        getContentPane().add(jenis);
        jenis.setBounds(1030, 60, 240, 30);

        nama.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(48, 56, 65));
        nama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                namaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(nama);
        nama.setBounds(1030, 30, 240, 30);

        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/karyawan.png"))); // NOI18N
        karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                karyawanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                karyawanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                karyawanMouseReleased(evt);
            }
        });
        getContentPane().add(karyawan);
        karyawan.setBounds(21, 415, 200, 30);

        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/retur.png"))); // NOI18N
        retur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                returMouseReleased(evt);
            }
        });
        getContentPane().add(retur);
        retur.setBounds(21, 320, 200, 30);

        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png"))); // NOI18N
        gudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gudangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gudangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gudangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gudangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gudangMouseReleased(evt);
            }
        });
        getContentPane().add(gudang);
        gudang.setBounds(21, 242, 200, 30);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/Transaction-beli.png"))); // NOI18N
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                transaksiMouseReleased(evt);
            }
        });
        getContentPane().add(transaksi);
        transaksi.setBounds(21, 201, 200, 30);

        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png"))); // NOI18N
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dashboardMouseReleased(evt);
            }
        });
        getContentPane().add(dashboard);
        dashboard.setBounds(21, 162, 200, 30);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(21, 494, 200, 30);

        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png"))); // NOI18N
        pengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengaturanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengaturanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengaturanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pengaturanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pengaturanMouseReleased(evt);
            }
        });
        getContentPane().add(pengaturan);
        pengaturan.setBounds(21, 454, 200, 30);

        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png"))); // NOI18N
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                riwayatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                riwayatMouseReleased(evt);
            }
        });
        getContentPane().add(riwayat);
        riwayat.setBounds(21, 280, 200, 30);

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/kosong.png"))); // NOI18N
        getContentPane().add(Menu);
        Menu.setBounds(0, 100, 218, 630);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/Header.png"))); // NOI18N
        header.setAlignmentY(0.0F);
        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 110);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/default (1).png"))); // NOI18N
        getContentPane().add(image);
        image.setBounds(938, 10, 75, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        tablebeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebeliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablebeli);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 270, 530, 380);

        bsup.setEditable(false);
        bsup.setForeground(new java.awt.Color(48, 56, 65));
        bsup.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        bsup.setMinimumSize(new java.awt.Dimension(221, 20));
        bsup.setPreferredSize(new java.awt.Dimension(221, 20));
        bsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupActionPerformed(evt);
            }
        });
        jPanel1.add(bsup);
        bsup.setBounds(270, 225, 530, 35);

        bgatot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bgatot.setForeground(new java.awt.Color(48, 56, 65));
        bgatot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(bgatot);
        bgatot.setBounds(550, 650, 240, 40);

        btfharga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfharga.setForeground(new java.awt.Color(48, 56, 65));
        btfharga.setBorder(null);
        btfharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btfhargaKeyReleased(evt);
            }
        });
        jPanel1.add(btfharga);
        btfharga.setBounds(850, 353, 360, 25);

        btfqty.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfqty.setForeground(new java.awt.Color(48, 56, 65));
        btfqty.setBorder(null);
        btfqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btfqtyKeyReleased(evt);
            }
        });
        jPanel1.add(btfqty);
        btfqty.setBounds(850, 413, 160, 25);

        btfsatuan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfsatuan.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(btfsatuan);
        btfsatuan.setBounds(1050, 413, 150, 25);

        ta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ta1.setForeground(new java.awt.Color(48, 56, 65));
        ta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ta1.setText("Grand Total :");
        jPanel1.add(ta1);
        ta1.setBounds(280, 650, 140, 40);

        btftotal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btftotal.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(btftotal);
        btftotal.setBounds(850, 477, 360, 25);

        btfnamabar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfnamabar.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(btfnamabar);
        btfnamabar.setBounds(850, 292, 360, 25);

        btfkdbar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfkdbar.setForeground(new java.awt.Color(48, 56, 65));
        jPanel1.add(btfkdbar);
        btfkdbar.setBounds(850, 230, 160, 27);

        btfkdbat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btfkdbat.setForeground(new java.awt.Color(48, 56, 65));
        btfkdbat.setBorder(null);
        btfkdbat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfkdbatActionPerformed(evt);
            }
        });
        btfkdbat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btfkdbatKeyReleased(evt);
            }
        });
        jPanel1.add(btfkdbat);
        btfkdbat.setBounds(1050, 230, 160, 27);

        btambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tambah-barang.png"))); // NOI18N
        btambahbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btambahbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btambahbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btambahbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btambahbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btambahbarMouseReleased(evt);
            }
        });
        jPanel1.add(btambahbar);
        btambahbar.setBounds(840, 540, 380, 40);

        bhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png"))); // NOI18N
        bhpsbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bhpsbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhpsbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhpsbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bhpsbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bhpsbarMouseReleased(evt);
            }
        });
        jPanel1.add(bhpsbar);
        bhpsbar.setBounds(1035, 590, 190, 40);

        beditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png"))); // NOI18N
        beditbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beditbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beditbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beditbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                beditbarMouseReleased(evt);
            }
        });
        jPanel1.add(beditbar);
        beditbar.setBounds(840, 590, 190, 40);

        bcheckout.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png"))); // NOI18N
        bcheckout.setAlignmentX(0.5F);
        bcheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bcheckoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bcheckoutMouseReleased(evt);
            }
        });
        jPanel1.add(bcheckout);
        bcheckout.setBounds(840, 640, 380, 40);

        ta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ta.setForeground(new java.awt.Color(48, 56, 65));
        ta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta.setText("Kode Transaksi :");
        jPanel1.add(ta);
        ta.setBounds(260, 117, 110, 50);

        bkdtrans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bkdtrans.setForeground(new java.awt.Color(48, 56, 65));
        bkdtrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkdtrans.setText("September");
        jPanel1.add(bkdtrans);
        bkdtrans.setBounds(370, 117, 170, 50);

        bcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png"))); // NOI18N
        bcaribar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcaribarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcaribarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bcaribarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bcaribarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bcaribarMouseReleased(evt);
            }
        });
        jPanel1.add(bcaribar);
        bcaribar.setBounds(560, 120, 390, 50);

        btgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btgl.setForeground(new java.awt.Color(48, 56, 65));
        btgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btgl.setText("September");
        jPanel1.add(btgl);
        btgl.setBounds(900, 117, 230, 50);

        bswitch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-jual.png"))); // NOI18N
        bswitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bswitchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bswitchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bswitchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bswitchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bswitchMouseReleased(evt);
            }
        });
        jPanel1.add(bswitch);
        bswitch.setBounds(1140, 120, 90, 50);

        jualatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/bgbeli.png"))); // NOI18N
        jPanel1.add(jualatas);
        jualatas.setBounds(252, 110, 990, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        checkout.setBackground(new java.awt.Color(255, 255, 255));
        checkout.setMinimumSize(new java.awt.Dimension(1280, 720));
        checkout.setLayout(null);

        co_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        co_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                co_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(co_table);

        checkout.add(jScrollPane5);
        jScrollPane5.setBounds(280, 210, 940, 230);

        co_isilblkiri.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        co_isilblkiri.setForeground(new java.awt.Color(48, 56, 65));
        checkout.add(co_isilblkiri);
        co_isilblkiri.setBounds(290, 628, 540, 25);

        ta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ta2.setForeground(new java.awt.Color(48, 56, 65));
        ta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta2.setText("Kode Transaksi :");
        checkout.add(ta2);
        ta2.setBounds(260, 117, 110, 50);

        co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png"))); // NOI18N
        co_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                co_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                co_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                co_backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                co_backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                co_backMouseReleased(evt);
            }
        });
        checkout.add(co_back);
        co_back.setBounds(990, 620, 210, 60);

        co_kdtrans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        co_kdtrans.setForeground(new java.awt.Color(48, 56, 65));
        co_kdtrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        co_kdtrans.setText("September");
        checkout.add(co_kdtrans);
        co_kdtrans.setBounds(370, 117, 170, 50);

        co_isilblkanan.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        co_isilblkanan.setForeground(new java.awt.Color(48, 56, 65));
        co_isilblkanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkout.add(co_isilblkanan);
        co_isilblkanan.setBounds(960, 510, 250, 100);

        co_lblgtot.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        co_lblgtot.setForeground(new java.awt.Color(48, 56, 65));
        checkout.add(co_lblgtot);
        co_lblgtot.setBounds(285, 520, 590, 50);

        co_tgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        co_tgl.setForeground(new java.awt.Color(48, 56, 65));
        co_tgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        co_tgl.setText("September");
        checkout.add(co_tgl);
        co_tgl.setBounds(990, 120, 230, 50);

        jualatas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cekoutbeli.png"))); // NOI18N
        checkout.add(jualatas1);
        jualatas1.setBounds(252, 110, 990, 590);

        getContentPane().add(checkout);
        checkout.setBounds(0, 0, 1280, 720);

        popupbeli.setBackground(new Color(0,0,0,20));
        popupbeli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        popupbeli.setFocusCycleRoot(true);
        popupbeli.setFocusTraversalPolicyProvider(true);
        popupbeli.setMinimumSize(new java.awt.Dimension(1016, 615));
        popupbeli.setLayout(null);

        tablepopbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepopbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepopbeliMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablepopbeli);

        popupbeli.add(jScrollPane4);
        jScrollPane4.setBounds(160, 90, 690, 430);

        popbelicari.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        popbelicari.setBorder(null);
        popbelicari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                popbelicariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                popbelicariFocusLost(evt);
            }
        });
        popbelicari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popbelicariActionPerformed(evt);
            }
        });
        popbelicari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                popbelicariKeyReleased(evt);
            }
        });
        popupbeli.add(popbelicari);
        popbelicari.setBounds(210, 40, 630, 30);

        h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/Search-bar-long.png"))); // NOI18N
        popupbeli.add(h);
        h.setBounds(160, 30, 700, 50);

        popbend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png"))); // NOI18N
        popbend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popbendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popbendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popbendMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popbendMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popbendMouseReleased(evt);
            }
        });
        popupbeli.add(popbend);
        popbend.setBounds(520, 530, 160, 50);

        popbtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png"))); // NOI18N
        popbtambahbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popbtambahbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popbtambahbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popbtambahbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popbtambahbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popbtambahbarMouseReleased(evt);
            }
        });
        popupbeli.add(popbtambahbar);
        popbtambahbar.setBounds(690, 530, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/bgpop.png"))); // NOI18N
        popupbeli.add(jLabel2);
        jLabel2.setBounds(110, 10, 810, 600);

        getContentPane().add(popupbeli);
        popupbeli.setBounds(246, 100, 1040, 620);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bswitchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bswitchMouseEntered
        // TODO add your handling code here:
bswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-jual-hover.png")));
    }//GEN-LAST:event_bswitchMouseEntered

    private void bswitchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bswitchMouseExited
        // TODO add your handling code here:
bswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-jual.png")));
    }//GEN-LAST:event_bswitchMouseExited

    private void btfkdbatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btfkdbatKeyReleased
        // TODO add your handling code here:
if (btfkdbat.getText().equals("")) {
} else {
    try {
            String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan " +
                    "WHERE barcode = '" + btfkdbat.getText() + "' ;";
            Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            res.next() ;
                btfkdbar.setText(res.getString(1));
                        btfnamabar.setText(res.getString(2));
                        btfsatuan.setText(res.getString(4));

                double qty = Double.parseDouble(btfqty.getText()), hrg = Double.parseDouble(btfharga.getText());
                Double tot = hrg * qty;
                btftotal.setText(String.valueOf(tot));
        } catch (Exception e) {
        }
}
    }//GEN-LAST:event_btfkdbatKeyReleased

    private void bcaribarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcaribarMouseClicked
        // TODO add your handling code here:
//popjualcari.set
popupbeli.setVisible(true);
popupbeli.requestFocus();
jPanel1.setVisible(false);

popbelicari.setForeground(new java.awt.Color(221,221,221));
popbelicari.setText("Cari Nama Barang");
settablepopjual();
    }//GEN-LAST:event_bcaribarMouseClicked

    private void popbelicariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popbelicariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_popbelicariActionPerformed

    private void popbendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbendMouseClicked
        // TODO add your handling code here:
popupbeli.setVisible(false);
popupbeli.requestFocus();
jPanel1.setVisible(true);
    }//GEN-LAST:event_popbendMouseClicked

    private void popbelicariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popbelicariFocusLost
        // TODO add your handling code here:
if (popbelicari.getText().equals("")) {
popbelicari.setForeground(new java.awt.Color(221,221,221));
popbelicari.setText("Cari Nama Barang");
} else {
}
    }//GEN-LAST:event_popbelicariFocusLost

    private void popbelicariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popbelicariFocusGained
        // TODO add your handling code here:
if (popbelicari.getText().equals("Cari Nama Barang")) {
popbelicari.setForeground(new java.awt.Color(51,51,51));
popbelicari.setText("");
} else {
}
    }//GEN-LAST:event_popbelicariFocusGained

    private void popbtambahbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbtambahbarMouseClicked
        // TODO add your handling code here:
        bkosong();
        if (jkdbar.equals("")) {
            panggilAlertMerah("Tambah Gagal !", "Pilih dulu barang dari table");
        } else {
            try {
                    String sql = "select barang.nama_barang, barang.barcode, satuan.satuan "
                    + "from barang join satuan on barang.id_satuan = satuan.id_satuan "
                    + "where barang.id_barang = '"+jkdbar+"' ;" ;
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.Statement stm=conn.createStatement();
                    java.sql.ResultSet res=stm.executeQuery(sql);
                    while (res.next()) {
                    btfkdbar.setText(jkdbar);
                    btfkdbat.setText(res.getString(2));
                    btfnamabar.setText(res.getString(1));
                    btfsatuan.setText(res.getString(3));
                    }
                } catch (Exception e) {
                }
        }
popupbeli.setVisible(false);
jPanel1.setVisible(true);
    }//GEN-LAST:event_popbtambahbarMouseClicked

    private void bhpsbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhpsbarMouseClicked
        // TODO add your handling code here:
    if (btfkdbar.getText().equals("")) {
            panggilAlertMerah("Hapus Gagal !", "Pilih dahulu barang yang ingin dihapus");
        } else {
                AlertPertanyaan obj = new AlertPertanyaan(this);
               obj.showMessage("Konfirmasi Hapus Barang", "apakah anda yakin ingin menghapus barang dengan Kode " + btfkdbar.getText() + " dari keranjang ?");
               if (obj.getMessageType() == AlertPertanyaan.MessageType.OK){
            
                try {
                    String sql = "DELETE FROM cart_pembelian where id_barang='" + btfkdbar.getText() + "'";
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    setTablebeli();
                    bkosong();
                } catch (Exception e) {
                    panggilAlertMerah("Hapus Gagal !", "penghapusan data pembelian barang gagal");
                }
            }
        }
    }//GEN-LAST:event_bhpsbarMouseClicked

    private void bcheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcheckoutMouseClicked
        // TODO add your handling code here:
        DefaultTableModel cartmodel = (DefaultTableModel) tablebeli.getModel();
        if (cartmodel.getRowCount ()==0) {
             panggilAlertMerah("Checkout Gagal !", "Keranjang masih kosong");
        } else {
               AlertPertanyaan obj = new AlertPertanyaan(this);
               obj.showMessage("Konfirmasi Checkout", "apakah anda yakin untuk checkout ?");
               if (obj.getMessageType() == AlertPertanyaan.MessageType.OK){
            bcekout();
            bkosong();
            mainco();
        }
    }
    }//GEN-LAST:event_bcheckoutMouseClicked

    private void popbelicariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popbelicariKeyReleased
        // TODO add your handling code here:
tablepopbeli.fixTable(jScrollPane4);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    
    try {
        int no=1;
        String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, barang.jumlah, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan "
                    +"WHERE nama_barang like '%" + popbelicari.getText() + "%' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5)
            });
        }
        tablepopbeli.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_popbelicariKeyReleased

    private void co_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseClicked
        // TODO add your handling code here:
            setTablebeli();
            setBkdtrans();
            checkout.setVisible(false);
            jPanel1.setVisible(true);
            setBtgl();
    }//GEN-LAST:event_co_backMouseClicked

    private void btfkdbatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfkdbatActionPerformed
        // TODO add your handling code here:
if (btfkdbat.getText().equals("")) {
} else { if (!btfkdbar.getText().equals("")) {
        btfharga.requestFocus();
        } else {
}
}
    }//GEN-LAST:event_btfkdbatActionPerformed

    private void tablepopbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepopbeliMouseClicked
        // TODO add your handling code here:
        int baris = tablepopbeli.rowAtPoint(evt.getPoint());
        jkdbar = tablepopbeli.getValueAt(baris, 0).toString();
    }//GEN-LAST:event_tablepopbeliMouseClicked

    private void tablebeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebeliMouseClicked
        // TODO add your handling code here:
int baris = tablebeli.rowAtPoint(evt.getPoint());
        btfkdbar.setText(tablebeli.getValueAt(baris, 0).toString());
        try {
            String sql = "select barcode from barang " +
                    "WHERE id_barang = '" + tablebeli.getValueAt(baris, 0).toString() + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            btfkdbat.setText(rs.getString("barcode"));

        } catch (Exception e) {
            e.printStackTrace();
        }
        if (tablebeli.getValueAt(baris, 1)==null) {
            btfnamabar.setText("");
        } else {
            btfnamabar.setText(tablebeli.getValueAt(baris, 1).toString());
        }
        if (tablebeli.getValueAt(baris, 2)==null) {
            btfharga.setText("");
        } else {
            btfharga.setText(tablebeli.getValueAt(baris, 2).toString());
        }
        if (tablebeli.getValueAt(baris, 3)==null) {
            btfqty.setText("");
        } else {
            btfqty.setText(tablebeli.getValueAt(baris, 3).toString());  
        }
        if (tablebeli.getValueAt(baris, 5)==null) {
            btftotal.setText("");
        } else {
            btftotal.setText(tablebeli.getValueAt(baris, 5).toString());
        }
        if (tablebeli.getValueAt(baris, 4)==null) {
            btfsatuan.setText("");
        } else {
            String sat= tablebeli.getValueAt(baris, 4).toString();
        try {
            String sql = "SELECT satuan from satuan "
                    + "where id_satuan = '" + sat + "';";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            btfsatuan.setText(rs.getString("satuan"));

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_tablebeliMouseClicked

    private void karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseEntered
        // TODO add your handling code here:
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/karyawan-hover.png")));
    }//GEN-LAST:event_karyawanMouseEntered

    private void karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseExited
        // TODO add your handling code here:
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/karyawan.png")));
    }//GEN-LAST:event_karyawanMouseExited

    private void karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMousePressed
        // TODO add your handling code here:
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/karyawan-clicked.png")));
    }//GEN-LAST:event_karyawanMousePressed

    private void karyawanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseReleased
        // TODO add your handling code here:
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/karyawan.png")));
    }//GEN-LAST:event_karyawanMouseReleased

    private void returMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseEntered
        // TODO add your handling code here:
        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/retur-hover.png")));
    }//GEN-LAST:event_returMouseEntered

    private void returMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseExited
        // TODO add your handling code here:
        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/retur.png")));
    }//GEN-LAST:event_returMouseExited

    private void returMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMousePressed
        // TODO add your handling code here:
        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/retur-clicked.png")));
    }//GEN-LAST:event_returMousePressed

    private void returMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseReleased
        // TODO add your handling code here:
        retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/retur.png")));
    }//GEN-LAST:event_returMouseReleased

    private void gudangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseEntered
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang-hover.png")));
    }//GEN-LAST:event_gudangMouseEntered

    private void gudangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseExited
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png")));
    }//GEN-LAST:event_gudangMouseExited

    private void gudangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMousePressed
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang-clicked.png")));
    }//GEN-LAST:event_gudangMousePressed

    private void gudangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseReleased
        // TODO add your handling code here:
        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/gudang.png")));
    }//GEN-LAST:event_gudangMouseReleased

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        TransaksiBeli Transaksijual = new TransaksiBeli();
        Transaksijual.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksiMouseClicked

    private void transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseEntered

    private void transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseExited

    private void transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMousePressed

    private void transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_transaksiMouseReleased

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard-hover.png")));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png")));
    }//GEN-LAST:event_dashboardMouseExited

    private void dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMousePressed
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard-clicked.png")));
    }//GEN-LAST:event_dashboardMousePressed

    private void dashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseReleased
        // TODO add your handling code here:
dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/dashboard.png")));
    }//GEN-LAST:event_dashboardMouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout-hover.png")));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout-hover.png")));
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        // TODO add your handling code here:
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/logout.png")));
    }//GEN-LAST:event_logoutMouseReleased

    private void pengaturanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseEntered
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan-hover.png")));
    }//GEN-LAST:event_pengaturanMouseEntered

    private void pengaturanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseExited
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png")));
    }//GEN-LAST:event_pengaturanMouseExited

    private void pengaturanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMousePressed
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan-clicked.png")));
    }//GEN-LAST:event_pengaturanMousePressed

    private void pengaturanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseReleased
        // TODO add your handling code here:
        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/pengaturan.png")));
    }//GEN-LAST:event_pengaturanMouseReleased

    private void riwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseEntered
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat-hover.png")));
    }//GEN-LAST:event_riwayatMouseEntered

    private void riwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseExited
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png")));
    }//GEN-LAST:event_riwayatMouseExited

    private void riwayatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMousePressed
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat-clicked.png")));
    }//GEN-LAST:event_riwayatMousePressed

    private void riwayatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseReleased
        // TODO add your handling code here:
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sideBar/riwayat.png")));
    }//GEN-LAST:event_riwayatMouseReleased

    private void bsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsupActionPerformed

    private void btfqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btfqtyKeyReleased
        // TODO add your handling code here:
if (btfharga.getText().equals("")) {
        } else {
            int hrg = Integer.parseInt(btfharga.getText());
            double qty = Double.parseDouble(btfqty.getText()), tot = hrg * qty;
            btftotal.setText(String.valueOf(tot));
        }
    }//GEN-LAST:event_btfqtyKeyReleased

    private void btambahbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btambahbarMouseClicked
        // TODO add your handling code here:

        if (btfkdbar.getText().equals("")) {
            panggilAlertMerah("Tambah Gagal !", "Pilih dahulu barang yang ingin ditambah");
        } else {
            String bar = "";
            Double harga = null, hrg, qty;
            try {
                String sqll = "SELECT id_barang, harga_beli FROM cart_pembelian where id_barang='" + btfkdbar.getText() + "' ;";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sqll);
                res.next();
                bar = res.getString("id_barang");
                harga = res.getDouble("harga_beli");
            } catch (Exception e) {
            }
             AlertPertanyaan obj = new AlertPertanyaan(this);  
            if (bar.equals(btfkdbar.getText())) {
                obj.showMessage("Barang sudah ada dalam Keranjang", "Apakah anda ingin menambahkan kuantitasnya saja ?");
               if (obj.getMessageType() == AlertPertanyaan.MessageType.OK){
                    qty = Double.parseDouble(btfqty.getText());
                    hrg = harga * qty;
                    try {
                        String sqll = "UPDATE cart_pembelian "
                                + "SET qty = qty+" + btfqty.getText()
                                + ", harga_total = harga_total+" + hrg
                                + " WHERE cart_pembelian.id_barang = '" + btfkdbar.getText() + "'";
                        java.sql.Connection conn = (Connection) Config.configDB();
                        java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                        pstl.execute();
                    } catch (Exception e) {
                    String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
                    }
                    bkosong();
                    setTablebeli();
                } else {

                }
            } else {
                try {
                    String sqll = "INSERT INTO `cart_pembelian` (`id_pembelian`, `id_barang`, `harga_beli`, `qty`, `harga_total`)" +
                            " VALUES ('" + bkdtrans.getText() + "', '"
                            + btfkdbar.getText() + "', '"
                            + btfharga.getText() + "', '"
                            + btfqty.getText() + "', '"
                            + btftotal.getText() + "'); ";
                    java.sql.Connection conn = (Connection) Config.configDB();
                    java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                    pstl.execute();
                bkosong();
                setTablebeli();
                } catch (Exception e) {
                    String c = e.getMessage().substring(0, 40);
                    panggilAlertMerah("Gagal !", c);
                }
            }

        }
    }//GEN-LAST:event_btambahbarMouseClicked

    private void beditbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditbarMouseClicked
        // TODO add your handling code here:
        if (btfkdbar.getText().equals("")) {
            panggilAlertMerah("Edit Gagal !", "Pilih dahulu barang yang ingin diedit");
        } else {
            try {
                String sqll = "UPDATE cart_pembelian "
                        + "SET harga_beli = '" + btfharga.getText()
                        + "', qty = '" + btfqty.getText()
                        + "', harga_total = '" + btftotal.getText()
                        + "' WHERE cart_pembelian.id_barang = '" + btfkdbar.getText() + "'";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
                pstl.execute();
            bkosong();
            setTablebeli();
            } catch (Exception e) {
                    String c = e.getMessage().substring(0, 40);
                    panggilAlertMerah("Gagal !", c);
            }

        }
    }//GEN-LAST:event_beditbarMouseClicked

    private void co_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_co_tableMouseClicked

    private void bswitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bswitchMouseClicked
        // TODO add your handling code here:
                    TransaksiJual Transaksijual = new TransaksiJual();
                    Transaksijual.nama.setText(nama.getText());
                    Transaksijual.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_bswitchMouseClicked

    private void btfhargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btfhargaKeyReleased
        // TODO add your handling code here:
            int hrg = Integer.parseInt(btfharga.getText());
            double qty = Double.parseDouble(btfqty.getText()), tot = hrg * qty;
            btftotal.setText(String.valueOf(tot));
    }//GEN-LAST:event_btfhargaKeyReleased

    private void popbendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbendMouseEntered
        // TODO add your handling code here:
popbend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali-hover.png")));
    }//GEN-LAST:event_popbendMouseEntered

    private void popbendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbendMouseExited
        // TODO add your handling code here:
popbend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png")));
    }//GEN-LAST:event_popbendMouseExited

    private void popbendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbendMousePressed
        // TODO add your handling code here:
popbend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali-clicked.png")));
    }//GEN-LAST:event_popbendMousePressed

    private void popbendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbendMouseReleased
        // TODO add your handling code here:
popbend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/kembali.png")));
    }//GEN-LAST:event_popbendMouseReleased

    private void popbtambahbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbtambahbarMouseEntered
        // TODO add your handling code here:
popbtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah-hover.png")));
    }//GEN-LAST:event_popbtambahbarMouseEntered

    private void popbtambahbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbtambahbarMouseExited
        // TODO add your handling code here:
popbtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png")));
    }//GEN-LAST:event_popbtambahbarMouseExited

    private void popbtambahbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbtambahbarMousePressed
        // TODO add your handling code here:
popbtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah-clicked.png")));
    }//GEN-LAST:event_popbtambahbarMousePressed

    private void popbtambahbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popbtambahbarMouseReleased
        // TODO add your handling code here:
popbtambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/popup/tambah.png")));
    }//GEN-LAST:event_popbtambahbarMouseReleased

    private void co_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseEntered
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali-hover.png")));
    }//GEN-LAST:event_co_backMouseEntered

    private void co_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseExited
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png")));
    }//GEN-LAST:event_co_backMouseExited

    private void co_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMousePressed
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali-clicked.png")));
    }//GEN-LAST:event_co_backMousePressed

    private void co_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_co_backMouseReleased
        // TODO add your handling code here:
co_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/kembali.png")));
    }//GEN-LAST:event_co_backMouseReleased

    private void bswitchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bswitchMousePressed
        // TODO add your handling code here:
bswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-jual-clicked.png")));
    }//GEN-LAST:event_bswitchMousePressed

    private void bswitchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bswitchMouseReleased
        // TODO add your handling code here:
bswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-jual.png")));
    }//GEN-LAST:event_bswitchMouseReleased

    private void btambahbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btambahbarMouseEntered
        // TODO add your handling code here:
btambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tambah-barang-hover.png")));
    }//GEN-LAST:event_btambahbarMouseEntered

    private void btambahbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btambahbarMouseExited
        // TODO add your handling code here:
btambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tambah-barang.png")));
    }//GEN-LAST:event_btambahbarMouseExited

    private void btambahbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btambahbarMousePressed
        // TODO add your handling code here:
btambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tambah-barang-clicked.png")));
    }//GEN-LAST:event_btambahbarMousePressed

    private void btambahbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btambahbarMouseReleased
        // TODO add your handling code here:
btambahbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/tambah-barang.png")));
    }//GEN-LAST:event_btambahbarMouseReleased

    private void beditbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditbarMouseEntered
        // TODO add your handling code here:
beditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang-hover.png")));
    }//GEN-LAST:event_beditbarMouseEntered

    private void beditbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditbarMouseExited
        // TODO add your handling code here:
beditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png")));
    }//GEN-LAST:event_beditbarMouseExited

    private void beditbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditbarMousePressed
        // TODO add your handling code here:
beditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang-clicked.png")));
    }//GEN-LAST:event_beditbarMousePressed

    private void beditbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditbarMouseReleased
        // TODO add your handling code here:
beditbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/edit-barang.png")));
    }//GEN-LAST:event_beditbarMouseReleased

    private void bhpsbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhpsbarMouseEntered
        // TODO add your handling code here:
bhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang-hover.png")));
    }//GEN-LAST:event_bhpsbarMouseEntered

    private void bhpsbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhpsbarMouseExited
        // TODO add your handling code here:
bhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png")));
    }//GEN-LAST:event_bhpsbarMouseExited

    private void bhpsbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhpsbarMousePressed
        // TODO add your handling code here:
bhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang-clicked.png")));
    }//GEN-LAST:event_bhpsbarMousePressed

    private void bhpsbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhpsbarMouseReleased
        // TODO add your handling code here:
bhpsbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/hapus-barang.png")));
    }//GEN-LAST:event_bhpsbarMouseReleased

    private void bcheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcheckoutMouseEntered
        // TODO add your handling code here:
bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout-hover.png")));
    }//GEN-LAST:event_bcheckoutMouseEntered

    private void bcheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcheckoutMouseExited
        // TODO add your handling code here:
bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png")));
    }//GEN-LAST:event_bcheckoutMouseExited

    private void bcheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcheckoutMousePressed
        // TODO add your handling code here:
bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout-clicked.png")));
    }//GEN-LAST:event_bcheckoutMousePressed

    private void bcheckoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcheckoutMouseReleased
        // TODO add your handling code here:
bcheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/btn-checkout.png")));
    }//GEN-LAST:event_bcheckoutMouseReleased

    private void bcaribarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcaribarMouseEntered
        // TODO add your handling code here:
bcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang-hover.png")));
    }//GEN-LAST:event_bcaribarMouseEntered

    private void bcaribarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcaribarMouseExited
        // TODO add your handling code here:
bcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png")));
    }//GEN-LAST:event_bcaribarMouseExited

    private void bcaribarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcaribarMousePressed
        // TODO add your handling code here:
bcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang-clicked.png")));
    }//GEN-LAST:event_bcaribarMousePressed

    private void bcaribarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcaribarMouseReleased
        // TODO add your handling code here:
bcaribar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Trans/cari-barang.png")));
    }//GEN-LAST:event_bcaribarMouseReleased

    private void namaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_namaAncestorAdded
        // TODO add your handling code here:
        setprofile();
    }//GEN-LAST:event_namaAncestorAdded

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
Dashboard dashboard = new Dashboard();
dashboard.nama.setText(nama.getText());
dashboard.setVisible(true);
this.dispose();

    }//GEN-LAST:event_dashboardMouseClicked

    private void gudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangMouseClicked
        // TODO add your handling code here:
                    Gudang gudang = new Gudang();
                    gudang.nama.setText(nama.getText());
                    gudang.setVisible(true);
                    this.dispose();

    }//GEN-LAST:event_gudangMouseClicked

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        // TODO add your handling code here:
TransaksiJual transaksijual = new TransaksiJual();
transaksijual.nama.setText(nama.getText());
transaksijual.setVisible(true);
this.dispose();

    }//GEN-LAST:event_riwayatMouseClicked

    private void returMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returMouseClicked
        // TODO add your handling code here:
                    Retur retur = new Retur();
                    retur.nama.setText(nama.getText());
                    retur.setVisible(true);
                    this.dispose();

    }//GEN-LAST:event_returMouseClicked

    private void karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseClicked
        // TODO add your handling code here:
Karyawan karyawan = new Karyawan();
karyawan.nama.setText(nama.getText());
karyawan.setVisible(true);
this.dispose();

    }//GEN-LAST:event_karyawanMouseClicked

    private void pengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengaturanMouseClicked
        // TODO add your handling code here:
                    Setting setting = new Setting();
                    setting.nama.setText(nama.getText());
                    setting.setVisible(true);
                    this.dispose();

    }//GEN-LAST:event_pengaturanMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        AlertPertanyaan obj = new AlertPertanyaan(this);
        obj.showMessage("Logout !", "Apakah Anda Ingin Logout ?");
        if (obj.getMessageType() == AlertPertanyaan.MessageType.OK) {
            Login login = new Login();
login.setVisible(true);
this.dispose();
        } else {
            
        }

    }//GEN-LAST:event_logoutMouseClicked

    void bcekout() {
        String sup = "";
        try {
            String sql = "SELECT id_supplier from supplier "
                    + "where nama_supplier = '" + bsup.getSelectedItem() + "';";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            rs.next();
            sup = rs.getString(1);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            String sqll = "insert into pembelian (id_pembelian, tanggal_transaksi, jam_transaksi, "
                    + "uang, id_pengguna, id_supplier) " +
                    "values ('" + bkdtrans.getText() + "', CURRENT_DATE, CURRENT_TIME, 0, "
                    + "'"+nama.getText()+"', '" + sup + "') ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstl = conn.prepareStatement(sqll);
            pstl.execute();
            String sql = "insert into detail_pembelian (`id_pembelian`, `id_barang`, "
                    + "`harga_beli`, `qty`, `harga_total`) "
                    + "SELECT id_pembelian, id_barang, harga_beli, qty, harga_total FROM cart_pembelian ;";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            String c = e.getMessage().substring(0, 36);
                    panggilAlertMerah("Gagal !", c);
        }
        try {
            String sql = "TRUNCATE TABLE cart_pembelian;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
        }
    }

    void bkosong() {
        btfkdbar.setText("");
        btfnamabar.setText(null);
        btfkdbat.setText(null);
        btfharga.setText(null);
        btfqty.setText(null);
        btfsatuan.setText(null);
        btftotal.setText(null);
        btfkdbat.requestFocus();
    }

private void setBsup() {
    String sql = "select * from supplier";
    try {
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while (res.next()) {
        bsup.addItem(res.getString("nama_supplier"));
    }
    } catch (Exception e) {
    }
}

    void setBkdtrans() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyy-");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        DateTimeFormatter dtff = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime tanggall = LocalDateTime.now();
        String aa = (dtff.format(tanggall));
        try {
            //--> melakukan eksekusi query untuk mengambil data dari tabel
            String sql = "SELECT MAX(id_pembelian) FROM pembelian " +
                    "WHERE tanggal_transaksi = '" + aa + "' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString(1) == null) {
                    bkdtrans.setText("TB-" + a + "001");
                } else {
                    rs.last();
                    String auto = rs.getString(1);
                    auto = auto.replace("TB-" + a, "");
                    int auto_id = Integer.parseInt(auto) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 3 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    bkdtrans.setText("TB-" + a + no);
                }
            }
            rs.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setBtgl() {
        String mm = "";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        DateTimeFormatter dtff = DateTimeFormatter.ofPattern("dd");
        LocalDateTime tanggall = LocalDateTime.now();
        String aa = (dtff.format(tanggall));
        DateTimeFormatter dtfff = DateTimeFormatter.ofPattern("yyyy");
        LocalDateTime tanggalll = LocalDateTime.now();
        String yyyy = (dtfff.format(tanggalll));
        int b = Integer.parseInt(a);
        switch (b) {
            case 1:
                mm = ("Januari");
                break;
            case 2:
                mm = ("Februari");
                break;
            case 3:
                mm = ("Maret");
                break;
            case 4:
                mm = ("April");
                break;
            case 5:
                mm = ("Mei");
                break;
            case 6:
                mm = ("Juni");
                break;
            case 7:
                mm = ("Juli");
                break;
            case 8:
                mm = ("Agustus");
                break;
            case 9:
                mm = ("September");
                break;
            case 10:
                mm = ("Oktober");
                break;
            case 11:
                mm = ("November");
                break;
            case 12:
                mm = ("Desember");
                break;
        }
        btgl.setText(aa + " " + mm + " " + yyyy);
    }

    void cekcartbeli() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyy-");
        LocalDateTime tanggal = LocalDateTime.now();
        String a = (dtf.format(tanggal));
        try {
            //--> melakukan eksekusi query untuk mengambil data dari tabel
            String sql = "SELECT MAX(id_pembelian) FROM cart_pembelian " +
                    "WHERE id_pembelian like '%" + a + "%' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString(1) == null) {
                    try {
                        String sqll = "TRUNCATE TABLE cart_pembelian;";
                        java.sql.Connection connn = (Connection) Config.configDB();
                        java.sql.PreparedStatement pstl = connn.prepareStatement(sqll);
                        pstl.execute();
                    } catch (Exception e) {
                    }
                } else {
//                    System.out.println("kosong");
                }
            }
            rs.close();
        } catch(Exception e){
            e.printStackTrace();
        }

    }

    void setTablebeli() {
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);

    tablebeli.fixTable(jScrollPane2);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode");
    model.addColumn("Barang");
    model.addColumn("Harga Beli");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    model.addColumn("Total");
    
    try {
        int no=1;
        String sql = "select cart_pembelian.id_barang, barang.nama_barang, " +
                    "cart_pembelian.harga_beli, cart_pembelian.qty, barang.id_satuan, cart_pembelian.harga_total " +
                    "from cart_pembelian join barang on cart_pembelian.id_barang = barang.id_barang"
                    + " where id_pembelian = '" + bkdtrans.getText() + "' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5),res.getString(6)
            });
        }
        tablebeli.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }

    try {
            String sql = "SELECT sum(harga_total) as total from cart_pembelian "
                    + "where id_pembelian = '"+bkdtrans.getText()+"' ;";
            java.sql.Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
                bgatot.setText("Rp. "+rs.getInt("total"));

        } catch (SQLException e) {
            e.printStackTrace();
        }

}

public final void settablepopjual() {
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);
tablepopbeli.fixTable(jScrollPane4);
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    
    try {
        int no=1;
        String sql = "select barang.id_barang, barang.nama_barang, barang.harga_jual, barang.jumlah, satuan.satuan"
                    + " from barang join satuan on barang.id_satuan = satuan.id_satuan ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5)
            });
        }
        tablepopbeli.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    void mainco() {
        co_kdtrans.setText(bkdtrans.getText());
        co_tgl.setText(btgl.getText());
        checkout.setVisible(true);
        jPanel1.setVisible(false);
        settableco();
        try {
            String sql = "SELECT pembelian.uang, supplier.nama_supplier from pembelian "
            + "join supplier on pembelian.id_supplier = supplier.id_supplier" +
                    " WHERE id_pembelian = '" + co_kdtrans.getText() + "' ;";
            Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            res.next();
            co_lblgtot.setText("Rp. " + res.getString(1));
            co_isilblkiri.setText(res.getString(2));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            String sql = "SELECT COUNT(id_barang) as totbar from detail_pembelian" +
                    " WHERE id_pembelian = '" + co_kdtrans.getText() + "' ;";
            Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            res.next();
            co_isilblkanan.setText(res.getString("totbar"));
        } catch (SQLException e) {
            e.printStackTrace();
        }
}

    void settableco() {
co_table.fixTable(jScrollPane5);
//        JTableHeader style = tablejual.getTableHeader();
//        tablejual.setRowHeight(25);
//        TableColumn col=tablejual.getColumnModel().getColumn(0);
//        col.setPreferredWidth(40);
//        TableColumn col1=tablejual.getColumnModel().getColumn(1);
//        col1.setPreferredWidth(100);
//        TableColumn col2=tablejual.getColumnModel().getColumn(2);
//        col2.setPreferredWidth(200);
//        TableColumn col3=tablejual.getColumnModel().getColumn(3);
//        col3.setPreferredWidth(74);
//        TableColumn col4=tablejual.getColumnModel().getColumn(4);
//        col4.setPreferredWidth(50);
//        TableColumn col5=tablejual.getColumnModel().getColumn(5);
//        col5.setPreferredWidth(150);

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Barang");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Kuantitas");
    model.addColumn("Satuan");
    model.addColumn("Harga Total");
    
    try {
        int no=1;
        String sql = "select detail_pembelian.id_barang, barang.nama_barang, " +
                    "detail_pembelian.harga_beli, detail_pembelian.qty, barang.id_satuan, detail_pembelian.harga_total " +
                    "from detail_pembelian join barang on detail_pembelian.id_barang = barang.id_barang"
                    + " where id_pembelian = '" + bkdtrans.getText() + "' ;";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
         model.addRow (new Object[] {res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5),res.getString(6)
            });
        }
        co_table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void jcheckoutActionPerformed(java.awt.event.ActionEvent evt) {

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiBeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel bcaribar;
    private javax.swing.JLabel bcheckout;
    private javax.swing.JLabel beditbar;
    private javax.swing.JLabel bgatot;
    private javax.swing.JLabel bhpsbar;
    private javax.swing.JLabel bkdtrans;
    private combo_suggestion.ComboBoxSuggestion bsup;
    private javax.swing.JLabel bswitch;
    private javax.swing.JLabel btambahbar;
    private javax.swing.JTextField btfharga;
    private javax.swing.JLabel btfkdbar;
    private javax.swing.JTextField btfkdbat;
    private javax.swing.JLabel btfnamabar;
    private javax.swing.JTextField btfqty;
    private javax.swing.JLabel btfsatuan;
    private javax.swing.JLabel btftotal;
    private javax.swing.JLabel btgl;
    private javax.swing.JPanel checkout;
    private javax.swing.JLabel co_back;
    private javax.swing.JLabel co_isilblkanan;
    private javax.swing.JLabel co_isilblkiri;
    private javax.swing.JLabel co_kdtrans;
    private javax.swing.JLabel co_lblgtot;
    private tabledark.TableDark co_table;
    private javax.swing.JLabel co_tgl;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel gudang;
    private javax.swing.JLabel h;
    private javax.swing.JLabel header;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel jualatas;
    private javax.swing.JLabel jualatas1;
    private javax.swing.JLabel karyawan;
    private javax.swing.JLabel logout;
    public javax.swing.JLabel nama;
    private javax.swing.JLabel pengaturan;
    private javax.swing.JTextField popbelicari;
    private javax.swing.JLabel popbend;
    private javax.swing.JLabel popbtambahbar;
    private javax.swing.JPanel popupbeli;
    private javax.swing.JLabel retur;
    private javax.swing.JLabel riwayat;
    private javax.swing.JLabel ta;
    private javax.swing.JLabel ta1;
    private javax.swing.JLabel ta2;
    private tabledark.TableDark tablebeli;
    private tabledark.TableDark tablepopbeli;
    private javax.swing.JLabel transaksi;
    // End of variables declaration//GEN-END:variables
}
